### ISSUE TITLE
pb build 

### ISSUE THREAD

**Issue by cmourzelas** [newrelic/sidecar#24]
Hello,

I'm trying to build the projet but i have this error : 

godep go build
godep: [WARNING]: godep should only be used inside a valid go package directory and
godep: [WARNING]: may not function correctly. You are probably outside of your $GOPATH.
godep: [WARNING]:       Current Directory: /root/sidecar
godep: [WARNING]:       $GOPATH: /root/sidecar
# github.com/newrelic/sidecar/discovery
src/github.com/newrelic/sidecar/discovery/docker_discovery.go:167: cannot use &container (type *"github.com/newrelic/sidecar/vendor/github.com/fsouza/go-dockerclient".APIContainers) as type *"github.com/Nitro/sidecar/vendor/github.com/fsouza/go-dockerclient".APIContainers in argument to service.ToService
godep: go exit status 2

I'm a begginer with "go" and don't know how to resolve it !

-- go version
go version go1.7.5 linux/amd64

**Comment by mihaitodor** [comment]
I think you should first go through [this document](https://golang.org/doc/code.html) and set the `$GOPATH` variable and the Go directory layout as instructed there. Then, you can use `go get github.com/newrelic/sidecar` to clone the repo into the appropriate location (`$GOPATH/src/github.com/newrelic/sidecar`). Please note that you don't need to invoke `godep` to build the project afterwards. `go build .` should suffice, given that you have all the dependencies set up. Otherwise, you can try running `go get ./…` first inside the sidecar source folder.

**Comment by relistan** [comment]
As @mihaitodor said, you need to set the `GOPATH` and have this project checked out inside it in the correct location. You may be able to do that by setting GOPATH and running `go get github.com/newrelic/sidecar`
