### ISSUE TITLE
Should SIDECAR_SEEDS include 127.0.0.1?

### ISSUE THREAD

**Issue by spuder** [newrelic/sidecar#35]
I'm having a hard time automating sidecar to detect other sidecar instances. 

Should SIDECAR_SEEDS include the host of the machine where sidecar is running? (e.g 127.0.0.1)

Does side car attempt to contact every server in the array for the intial seed? Or does it only use the first succesful ip address?

**Comment by mihaitodor** [comment]
Hi @spuder. Thanks for the interest in trying out Sidecar!

> I'm having a hard time automating sidecar to detect other sidecar instances.

Could you please provide some context / details about your setup / requirements?

> Should SIDECAR_SEEDS include the host of the machine where sidecar is running? (e.g 127.0.0.1)

To quote the documentation: "You always need to supply at least one IP address or hostname with the --cluster-ip argument. If are running solo, or are the first member, this can be your own hostname. You may specify the argument multiple times to have multiple hosts. It is recommended to use more than one when possible."

Basically, don't use `127.0.0.1`, since that's not a routable IP address. Use the network IPs of your hosts. If your cluster is not too big, you can just stick the IPs of all the Sidecar hosts from your cluster into the `SIDECAR_SEEDS` env var OR into the `--cluster-ip` argument as a comma separated list. Note that the `--cluster-ip` argument simply [overwrites](https://github.com/Nitro/sidecar/blob/fc683d5f91ff080c323d82f120d806350f45bb05/main.go#L45) the values passed in the `SIDECAR_SEEDS` env var (I think we should clarify this in the docs @relistan).

Sidecar uses [our own fork](https://github.com/Nitro/memberlist) of `hashicorp/memberlist` for managing cluster membership and member failure detection using a gossip based protocol. [Here](https://github.com/Nitro/sidecar/blob/fc683d5f91ff080c323d82f120d806350f45bb05/main.go#L293) and [here](https://github.com/Nitro/memberlist/blob/cfac2b5cf519ec17fd0704afe1f80b9d7df2d60e/memberlist.go#L202) you can see that Sidecar will not start up unless it manages to connect successfully to at least one host from `SIDECAR_SEEDS` or `--cluster-ip`. If no host is running, then you want to avoid a split brain situation by spinning up just one host first and then start the rest, making sure that they have the IP of the first host among their configured seeds.

Please note that Memberlist requires both TCP and UDP protocols enabled (see [here](https://github.com/Nitro/memberlist/blob/cfac2b5cf519ec17fd0704afe1f80b9d7df2d60e/memberlist.go#L277) for details) on port 7946, since both the [BindPort](https://github.com/Nitro/memberlist/blob/cfac2b5cf519ec17fd0704afe1f80b9d7df2d60e/config.go#L245) and [AdvertisePort](https://github.com/Nitro/memberlist/blob/cfac2b5cf519ec17fd0704afe1f80b9d7df2d60e/config.go#L247) are set by default to this value and Sidecar doesn't expose them as configuration parameters. Unfortunately, this is not captured in the documentation of Sidecar (cc @relistan).

> Does side car attempt to contact every server in the array for the intial seed? Or does it only use the first succesful ip address?

Yes, Memberlist tries to contact every specified seed over port 7946 through both TCP and UDP ([it tries UDP first](https://github.com/Nitro/sidecar/blob/fc683d5f91ff080c323d82f120d806350f45bb05/main.go#L234)), as explained above. See [here](https://github.com/Nitro/memberlist/blob/cfac2b5cf519ec17fd0704afe1f80b9d7df2d60e/memberlist.go#L169-L206) for details. Hence, if the list of seeds is too large, it might take a while for Sidecar to start.

Please let us know if you have more questions or if you have any other issues running Sidecar.

PS: The official Sidecar repo is now located in the [Nitro fork](https://github.com/Nitro/sidecar), but we're keeping this one updated as well for the time being.

**Comment by spuder** [comment]
Thank you for the clarification. 

>Could you please provide some context / details about your setup / requirements?

We are using chef to setup the nodes that manage the docker containers. The chef cookbook dynamically figures out the ip addresses of other nodes in the cluster. I'm finding that frequently sidecar just will not start. 

Since we have many nodes in the cluster, would it be better to point all new sidecar nodes to a single ip, or would it be acceptable to point all of them to all other machines ( 10 - 100)

>The official Sidecar repo is now located in the Nitro fork, but we're keeping this one updated as well for the time being.

So should I send documentation merge requests to that git repo, not this one?

**Comment by mihaitodor** [comment]
> Since we have many nodes in the cluster, would it be better to point all new sidecar nodes to a single ip, or would it be acceptable to point all of them to all other machines ( 10 - 100)

It depends on the assumptions that you make. If you have sufficient confidence that the hardcoded list of seed nodes will always contain at least one healthy and running instance of Sidecar, then that should be good enough. For us, since we have a small Mesos cluster orchestrated by Singularity, it was annoying to deploy the first instance of Sidecar, because we have no control over the host on which Mesos places it. So if, for some reason, we had to redeploy the entire cluster from scratch, we had a few situations where Mesos would place the first Sidecar instance on a node that wasn't among the list of seed nodes and then it wouldn't start, causing the entire deploy to fail. To avoid such situations with minimal effort, we just added all the nodes into the seeds. Because there are ~10 nodes currently, the start times are negligible. For 100 nodes, indeed, Sidecar might take too much time to start up, since it will try to connect to all of them sequentially (as you can see [here](https://github.com/Nitro/memberlist/blob/cfac2b5cf519ec17fd0704afe1f80b9d7df2d60e/memberlist.go#L169-L206)), so you'll probably need to use fewer seeds and be careful when redeploying / recreating the cluster.

> So should I send documentation merge requests to that git repo, not this one?
Thanks for those PRs! I think @relistan would prefer if you send them to that repo if you don't mind. I'll let him review them before merging.

**Comment by relistan** [comment]
Thanks @spuder and @mihaitodor. I'll merge those PRs here, but the main repo for this project is (as stated in the README) the Nitro repo, not this one. I no longer have the ability to change the New Relic repo to redirect there.
