### ISSUE TITLE
What causes `unable to spawn ./run - waiting 10 seconds`

### ISSUE THREAD

**Issue by spuder** [newrelic/sidecar#38]
I've been trying for weeks to get sidecar working. I frequently get this error when running inside of a docker container

```
s6-supervise (child): fatal: unable to exec run: No such file or directory
s6-supervise sidecar.svc: warning: unable to spawn ./run - waiting 10 seconds
```

I find if I reboot the host, the error often goes away. 

Looking for any ideas on why this happens

```
time="2018-02-05T20:44:54Z" level=info msg="State change event from dev-ndtweb01"
time="2018-02-05T20:44:56Z" level=info msg="State change event from dev-ndtweb01"
time="2018-02-05T20:46:11Z" level=info msg="State change event from dev-ndtweb01"
time="2018-02-05T20:46:12Z" level=info msg="State change event from dev-ndtweb01"
time="2018-02-05T20:46:14Z" level=info msg="State change event from dev-ndtweb01"
time="2018-02-05T20:47:09Z" level=info msg="Deleting 56a6ba98a1f0 based on Docker 'die' event\n"
time="2018-02-05T20:47:10Z" level=info msg="Adding health check: External (ID: 56a6ba98a1f0), Args: /bin/ps"
time="2018-02-05T20:47:10Z" level=info msg="Deleting 56a6ba98a1f0 based on Docker 'stop' event\n"
time="2018-02-05T20:47:10Z" level=warning msg="Tombstoning 56a6ba98a1f0"
time="2018-02-05T20:47:10Z" level=info msg="State change event from dev-ndtapi01"
Container shutting down
s6-svscan: warning: unable to exec finish script .s6-svscan/finish: No such file or directory
s6-svscan: warning: executing into .s6-svscan/crash
s6-supervise (child): fatal: unable to exec run: No such file or directory
s6-supervise sidecar.svc: warning: unable to spawn ./run - waiting 10 seconds
s6-supervise sidecar.svc: warning: unable to spawn ./run - waiting 10 seconds
s6-supervise (child): fatal: unable to exec run: No such file or directory
s6-supervise (child): fatal: unable to exec run: No such file or directory
s6-supervise sidecar.svc: warning: unable to spawn ./run - waiting 10 seconds
s6-supervise (child): fatal: unable to exec run: No such file or directory
s6-supervise sidecar.svc: warning: unable to spawn ./run - waiting 10 seconds
s6-supervise (child): fatal: unable to exec run: No such file or directory
s6-supervise sidecar.svc: warning: unable to spawn ./run - waiting 10 seconds
```

**Comment by relistan** [comment]
Sorry to hear that you are having issues getting it working. We run it in production using the `gonitro/sidecar` containers. As for this issue, I'm not sure what's going on there... never seen that before. It _looks_ like you are shutting down the container and then restarting it? Are you using the `gonitro/sidecar` container, or your own? It looks like Sidecar was working until it was somehow restarted in an unclean way. Some more insight into the container you're running would help me identify what might be wrong.

FYI, as it says in the README, this it not the main repo for this project and I don't watch it so you'll get faster response in the future if you post issues on the Nitro fork. I no longer have admin privileges on this repo and can't redirect from here to Nitro.

**Comment by spuder** [comment]
Yes I'm aware this isn't the main project, however the nitro repo has issues disabled. Figured I'd reach out to anyone one more time before we give up on sidecar. 

We are using the gonitro/sidecar docker container. 

There is nothing that should be stopping and starting the container. 

I'm not really sure if there is enough information here, and I'm not sure where else to look. I'll close this until I can find any additional info.

**Comment by mihaitodor** [comment]
@spuder

> Yes I'm aware this isn't the main project, however the nitro repo has issues disabled.

Oops, sorry about that! I enabled the issues section just now for nitro/sidecar. It looks like GH doesn't enable it by default for forks and we didn't notice :(

> Figured I'd reach out to anyone one more time before we give up on sidecar.

Hope we can help you to get it to work. It really shouldn't be all that painful to set up and we'd love to hear that other people end up using it.

> "Container shutting down"

This message comes from [here](https://github.com/newrelic/sidecar/blob/master/docker/s6/services/.s6-svscan/crash) and I can replicate your message to some extent by starting the container locally and then stopping it with `docker stop`:
```
s6-svscan: warning: unable to exec finish script .s6-svscan/finish: No such file or directory
s6-svscan: warning: executing into .s6-svscan/crash
Container shutting down
```

I'm not sure why you got `Container shutting down` pop up before `s6-svscan: warning: executing into .s6-svscan/crash`. Maybe Docker is not ordering log messages properly?...

Anyway, I am suspecting that maybe your cluster management / orchestration is shutting down & restarting the container, because it seems to be shutting down gracefully. A graceful shutdown will make s6 try to first execute `.s6-svscan/finish` and, since it can't find it, it will execute `.s6-svscan/crash`. This is a bit confusing, so I'll take it as a TODO to add a `finish` script in there.

> s6-supervise (child): fatal: unable to exec run: No such file or directory
> s6-supervise sidecar.svc: warning: unable to spawn ./run - waiting 10 seconds

The only way I can reproduce these is by going into the container as root and manually removing `/etc/services/sidecar.svc/run` and restarting the Sidecar service:
```
rm /etc/services/sidecar.svc/run
s6-svc -d /etc/services/sidecar.svc/
s6-svc -u /etc/services/sidecar.svc/
```

I can't imagine what might cause this to happen automatically in your environment. Maybe some Docker filesystem corruption? Are you doing some volume mounting from the host filesystem when running this container?

As a test, could you maybe try to reproduce the above situation again and confirm that `/etc/services/sidecar.svc/run` is missing in the container?

What operating system are you using, which version of Docker and what Docker storage driver?

**Comment by relistan** [comment]
@spuder sorry, not sure how the GitHub issues were disabled on the Nitro repo. That's a bummer. @mihaitodor enabled them now. I can't see how those logs messages appear in that order or how the run script is missing. We run this container on all of our nodes. These lines are ugly, but safely ignored:
```
s6-svscan: warning: unable to exec finish script .s6-svscan/finish: No such file or directory
s6-svscan: warning: executing into .s6-svscan/crash
```

However, as @mihaitodor  said, that indicates that s6 itself is shutting down inside the container. That basically only happens when something kills the container. If it were a problem with Sidecar, S6 would just restart it inside the container. The fact that S6 is being told to shutdown indicates some issue with your Docker install or your orchestrator/deployment system. Are you by chance seeing OOM Killer messages in `dmesg`? That's another likely culprit if you, for example, have memory limits enabled on the container.

**Comment by spuder** [comment]
Thanks for the information. 

I've identified what was 'stoping' the docker container, we are using chef to start the container, and the environment variables were a hash. On every chef run, the order of the environment variables could change which would trigger a restart. 

I've fixed the cookbook to alphebetize the environment variables, and I haven't seen any errors recently.

**Comment by mihaitodor** [comment]
That's great to hear @spuder! Thanks for letting us know. Don't hesitate to reach out if you run into trouble again.
